send_raw:
  target:
    device:
      integration: lg_tv_serial
    entity:
      integration: lg_tv_serial
  fields:
    command1:
      example: k
      required: true
      selector:
        text:
    command2:
      example: e
      required: true
      selector:
        text:
    data0:
      example: 1
      required: true
      selector:
        text:
    data1:
      example: ""
      required: false
      selector:
        text:
    data2:
      example: ""
      required: false
      selector:
        text:
    data3:
      example: ""
      required: false
      selector:
        text:
    data4:
      example: ""
      required: false
      selector:
        text:
    data5:
      example: ""
      required: false
      selector:
        text:
